### ISSUE TITLE
dequeue isn't doing it's job

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#20] opened 2013-02-24 16:20 UTC
```
 when "*forget"
   ((client.user.playlist.songs)[0]).dequeue
   client.user.playlist.update
   client.room.say(trigger['response'])
```

The internal playlist is updating correctly and showing what is next up, but the song isn't actually being removed from the play queue on turntable ( *nextup shows what should be right, but instead turntable plays the song that should have been deleted )

Any ideas?

**Comment by obrie** [comment] 2013-02-24 16:29
This is a dupe of #21 -- I'll rename the method to avoid the confusion.

**Closed as completed by obrie** 2013-02-24 16:29 UTC

**Comment by StephanieSunshine** [comment] 2013-02-24 16:31
No worries, it seems to me it's better that I update my code then for you to change the structure again.  Again thanks for everything!
