### ISSUE TITLE
client.song.skip failing

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#11] opened 2013-01-09 18:15 UTC
```
if level_1_acl.include?(message.sender.id) && message.content =~ /^\/skip$/
        client.song.skip
        client.room.say("Skipping")
end
```

D, [2013-01-09T10:07:47.000194 #5490] DEBUG -- : Message received: {"command"=>"speak", "userid"=>"4ea8d05fa3f751271d024366", "name"=>"", "roomid"=>"50b9c49faaa5cd76060cdb84", "text"=>"/skip"}
E, [2013-01-09T10:07:47.001192 #5490] ERROR -- : wrong number of arguments (0 for 1)
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/client.rb:398:in `song'
./seriousBot.rb:131:in`block (2 levels) in <main>'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/handler.rb:51:in `call'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/handler.rb:51:in`block in run'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/handler.rb:49:in `each'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/handler.rb:49:in`run'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/client.rb:453:in `block in on_message'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/client.rb:452:in`each'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/client.rb:452:in `on_message'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/client.rb:102:in`block in connect'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/connection.rb:130:in `call'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/connection.rb:130:in`block in dispatch'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler.rb:89:in `call'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler.rb:89:in`block (2 levels) in run'
/var/lib/gems/1.9.1/gems/em-synchrony-1.0.2/lib/em-synchrony.rb:26:in `call'
/var/lib/gems/1.9.1/gems/em-synchrony-1.0.2/lib/em-synchrony.rb:26:in`block (2 levels) in synchrony'

If I use song.skip instead of client.song.skip I get:

E, [2013-01-09T10:10:22.135381 #5490] ERROR -- : undefined local variable or method `song' for main:Object
./seriousBot.rb:131:in`block (2 levels) in <main>'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/handler.rb:51:in `call'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/handler.rb:51:in`block in run'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/handler.rb:49:in `each'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/handler.rb:49:in`run'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/client.rb:453:in `block in on_message'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/client.rb:452:in`each'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/client.rb:452:in `on_message'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/client.rb:102:in`block in connect'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/connection.rb:130:in `call'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler/connection.rb:130:in`block in dispatch'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler.rb:89:in `call'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler.rb:89:in`block (2 levels) in run'
/var/lib/gems/1.9.1/gems/em-synchrony-1.0.2/lib/em-synchrony.rb:26:in `call'
/var/lib/gems/1.9.1/gems/em-synchrony-1.0.2/lib/em-synchrony.rb:26:in`block (2 levels) in synchrony'

I found song.skip at the botom of the README.md in the first code block example

**Comment by obrie** [comment] 2013-01-10 05:47
This is a  dupe of #8 -- same issue

**Closed as completed by obrie** 2013-01-10 05:47 UTC
